/**
 * Addon manifests.
 *
 * An addon is a folder with an `addon.json` and a script beside it. The
 * manifest is the whole contract: it names the addon, says which file to run,
 * and declares which version of the addon API it was written against. Nothing
 * else about an addon is trusted until the manifest has been read and checked,
 * because everything downstream - the folder name on disk, the storage file,
 * the command namespace - is derived from the `id` in here.
 *
 * Validation is deliberately strict and total. A manifest is written by hand or
 * generated by an assistant, so the failure mode being guarded against is not
 * malice but a typo, and the useful response to a typo is a sentence naming the
 * field rather than an addon that half-loads.
 */
import fs from 'node:fs';
import path from 'node:path';

/**
 * The addon API version this build speaks.
 *
 * Bumped when the shape of the `flora` object changes in a way that would break
 * an existing addon. An addon declaring a higher number than this is refused
 * with a message saying so, rather than being loaded and failing somewhere
 * less legible.
 */
export const API_VERSION = 1;

/** Lowercase, digits and dashes. Used as a filename, so no dots or separators. */
const ID_SHAPE = /^[a-z0-9][a-z0-9-]{1,38}$/;

const MANIFEST_FILE = 'addon.json';

/** Fields every manifest must carry, with the type each has to be. */
const REQUIRED = {
  id: 'string',
  name: 'string',
  version: 'string',
  description: 'string'
};

/**
 * Read and check one addon folder.
 *
 * Returns `{ ok: true, manifest }` or `{ ok: false, error }` rather than
 * throwing: a broken addon in the folder must not stop the other twenty from
 * loading, so the caller collects failures and shows them in the UI beside the
 * addons that did load.
 */
export function readManifest(dir) {
  const file = path.join(dir, MANIFEST_FILE);

  let text;
  try {
    text = fs.readFileSync(file, 'utf8');
  } catch {
    return { ok: false, error: `No ${MANIFEST_FILE} in this folder.` };
  }

  let raw;
  try {
    raw = JSON.parse(text);
  } catch (err) {
    return { ok: false, error: `${MANIFEST_FILE} is not valid JSON: ${err.message}` };
  }

  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    return { ok: false, error: `${MANIFEST_FILE} must contain a single JSON object.` };
  }

  for (const [field, type] of Object.entries(REQUIRED)) {
    if (typeof raw[field] !== type || !String(raw[field]).trim()) {
      return { ok: false, error: `"${field}" is required and must be a non-empty ${type}.` };
    }
  }

  if (!ID_SHAPE.test(raw.id)) {
    return { ok: false, error: '"id" must be 2 to 39 characters of lowercase letters, digits and dashes.' };
  }

  // An addon written against a newer API than this build has is a real
  // possibility the moment the format changes, and it deserves better than a
  // TypeError from three frames deep.
  const api = raw.api === undefined ? 1 : Number(raw.api);
  if (!Number.isInteger(api) || api < 1) {
    return { ok: false, error: '"api" must be a positive whole number.' };
  }
  if (api > API_VERSION) {
    return {
      ok: false,
      error: `This addon needs addon API ${api}, and flora speaks ${API_VERSION}. Update flora.`
    };
  }

  const main = typeof raw.main === 'string' && raw.main.trim() ? raw.main.trim() : 'index.js';

  // The entry point is resolved inside the addon's own folder and nowhere else.
  // Without this a manifest could point at `../../../secret.key` and the loader
  // would hand the addon a path out of its own directory.
  const entry = path.resolve(dir, main);
  const within = path.relative(dir, entry);
  if (within.startsWith('..') || path.isAbsolute(within)) {
    return { ok: false, error: '"main" must point at a file inside the addon folder.' };
  }
  if (!fs.existsSync(entry)) {
    return { ok: false, error: `"main" points at ${main}, which is not there.` };
  }

  return {
    ok: true,
    manifest: {
      id: raw.id,
      name: String(raw.name).trim(),
      version: String(raw.version).trim(),
      description: String(raw.description).trim(),
      author: typeof raw.author === 'string' ? raw.author.trim() : '',
      homepage: typeof raw.homepage === 'string' ? raw.homepage.trim() : '',
      api,
      main,
      entry,
      dir,
      // Bundled addons are the ones flora ships. They can be turned off but not
      // deleted, because deleting one would only mean it came back on the next
      // update and the UI would have lied about it in the meantime.
      builtin: raw.builtin === true,
      // Off by default unless the manifest asks otherwise, which only a bundled
      // addon may do. A dropped-in addon starts disabled so that copying a
      // folder into the addons directory is not itself an act of consent.
      defaultEnabled: raw.builtin === true && raw.defaultEnabled !== false
    }
  };
}

/** A one-line summary of an addon folder for a list or an error message. */
export function describeFolder(dir) {
  return path.basename(dir);
}
