/**
 * The addon-authoring prompt.
 *
 * One block of text, offered in Settings with a copy button, written to be
 * pasted into an assistant along with whatever the person wants their addon to
 * do. It lives here rather than in the renderer so it sits in the same folder
 * as the API it documents: when a method is added to `buildApi`, the paragraph
 * that promises it is one file away instead of one repository away.
 *
 * It is deliberately a complete and literal description rather than a summary.
 * The reader is an assistant that has never seen flora and cannot look it up,
 * so anything left out is something it will invent - and an invented method
 * name fails inside a sandbox with no stack trace the author can act on.
 */

const LINES = [
  'You are writing an addon for flora, a desktop Minecraft bot manager.',
  'An addon is a folder containing exactly two files: addon.json and index.js.',
  'Write both files and nothing else.',
  '',
  '## addon.json',
  '',
  'A JSON object with these fields:',
  '',
  '  id           required. 2-39 chars, lowercase letters, digits and dashes only.',
  '               This becomes a folder name and a filename, so no dots or spaces.',
  '  name         required. Shown in the app. Any text.',
  '  version      required. Any text, for example "1.0.0".',
  '  description  required. One sentence, shown under the name in Settings.',
  '  author       optional. Your name or handle.',
  '  homepage       optional. A URL.',
  '  api          optional. The addon API version. Use 1.',
  '  main         optional. The entry file. Defaults to "index.js".',
  '',
  '## index.js',
  '',
  'A plain script, not an ES module. Do not write import, require, export or',
  'module.exports - none of them exist and any of them will stop the addon from',
  'loading. The script is run once with a single global in scope called `flora`.',
  '',
  'The script may also declare two optional functions, which are called for you:',
  '',
  '  function activate()   {}   // after the script body has run',
  '  function deactivate() {}   // when the addon is switched off or reloaded',
  '',
  '## What is and is not available',
  '',
  'Available: the `flora` object described below, `console.log/warn/error`, and',
  'the normal JavaScript built-ins (Object, Array, JSON, Math, Promise, Map, Set,',
  'Date, RegExp, setTimeout, and so on).',
  '',
  'NOT available: require, import, process, fetch, XMLHttpRequest, fs, path, and',
  'any way to read a file or open a network connection. eval and new Function are',
  'disabled. Do not write code that depends on any of these.',
  '',
  '## The flora object',
  '',
  'flora.id        string   the id from your manifest',
  'flora.name      string   the name from your manifest',
  'flora.version   string   the version from your manifest',
  'flora.log(message, level)          level is "info", "warn", "error" or "debug"',
  'flora.warn(message)',
  'flora.error(message)',
  '',
  'flora.commands.register({ name, usage, summary, run })',
  '    Adds a command the bot answers to in server chat. Called when you register',
  '    it, so call it at the top level of your script.',
  '      name     lowercase letters, digits and dashes. Up to 24 chars. Must not',
  '               clash with a built-in: help, say, come, follow, stop, status.',
  '      usage    what to show in the help list, without the prefix, e.g. "greet <name>"',
  '      summary  one short line describing it',
  '      run(bot, args, ctx)   called when someone whitelisted types the command.',
  '          bot   the live mineflayer bot instance. bot.chat(text), bot.whisper(name, text),',
  '                bot.entity.position, bot.players, bot.pathfinder, bot.health, bot.food.',
  '          args  array of the words typed after the command name',
  '          ctx   { username, prefix, server, accountId, log(level, text) }',
  '                ctx.username is the PLAYER who asked, not the bot',
  '                ctx.log writes a line into flora\'s console for that bot',
  '',
  'flora.commands.unregister(name)    removes a command you registered',
  '',
  'flora.on(event, handler)           listen for something happening to a bot.',
  '    Returns a function that unsubscribes. The event names are:',
  '      "bot:login"    { accountId, username, server, bot }',
  '      "bot:spawn"    { accountId, username, server, bot }',
  '      "bot:chat"     { accountId, username, server, bot, username, message }',
  '                     username/message here are the PLAYER and what they said',
  '      "bot:message"  { accountId, bot, message }   system and action-bar text',
  '      "bot:kicked"   { accountId, bot, reason }',
  '      "bot:error"    { accountId, bot, error }',
  '      "bot:end"      { accountId, bot, reason }    the socket closed',
  '',
  'flora.bots.list()                  every bot, as { accountId, username, server, status }',
  'flora.bots.online()                only the ones with status "online"',
  'flora.bots.get(accountId)          the live record for one bot, or null',
  'flora.bots.chat(accountId, text)   make a bot say something',
  'flora.bots.whisper(accountId, target, text)',
  'flora.bots.command(accountId, text)  run a server command as the bot, without the slash',
  'flora.bots.log(accountId, text, level)  write a line into that bot\'s console',
  '',
  'flora.settings.define({ "mySetting": { type, label, help, default } })',
  '    Declares settings for your addon. They appear in Settings under your addon.',
  '    type is "bool", "number", "string" or "enum". For "enum" also give',
  '    options: ["a", "b"]. For "number" you may give min and max.',
  'flora.settings.get(key)            the current value',
  'flora.settings.set(key, value)     save a new value',
  '',
  'flora.store.get(key, fallback)     your own storage. Persists across restarts.',
  'flora.store.set(key, value)        value must be JSON-serialisable',
  'flora.store.delete(key)',
  'flora.store.all()',
  '',
  'flora.every(milliseconds, fn)      run fn on a timer. Returns a function that stops it.',
  'flora.after(milliseconds, fn)      run fn once, later.',
  '',
  '## Worked example',
  '',
  'An addon that greets players and adds a command to make a bot dance.',
  '',
  '  // addon.json',
  '  {',
  '    "id": "greeter",',
  '    "name": "Greeter",',
  '    "version": "1.0.0",',
  '    "description": "Says hello to players who come near, and adds a dance command.",',
  '    "api": 1',
  '  }',
  '',
  '  // index.js',
  '  flora.commands.register({',
  '    name: "dance",',
  '    usage: "dance",',
  '    summary: "Make the bot jump about for a moment",',
  '    run(bot, args, ctx) {',
  '      let hops = 0;',
  '      const stop = flora.every(300, () => {',
  '        if (hops++ > 8) { stop(); return; }',
  '        if (bot.entity && bot.entity.onGround) bot.setControlState("jump", true);',
  '        setTimeout(() => { try { bot.setControlState("jump", false); } catch (e) {} }, 120);',
  '      });',
  '      ctx.log("command", bot.username + " is dancing for " + ctx.username);',
  '    }',
  '  });',
  '',
  '  flora.settings.define({',
  '    greeting: { type: "string", label: "Greeting", default: "Hello there!" }',
  '  });',
  '',
  '  flora.on("bot:chat", (event) => {',
  '    const text = flora.settings.get("greeting");',
  '    if (event.message.toLowerCase().indexOf("hi") === 0) {',
  '      flora.bots.chat(event.accountId, event.username + ": " + text);',
  '    }',
  '  });',
  '',
  '## Rules to follow',
  '',
  '1. Write only the two files. No package.json, no README, no dependencies.',
  '2. Never use import, require, export or module.exports.',
  '3. Wrap anything that touches the network or a bot in a try/catch - a bot can',
  '   disconnect at any moment and a thrown error is logged against your addon.',
  '4. Do not assume a bot exists. Check flora.bots.online() first, or guard on the',
  '   event you were given.',
  '5. Keep replies short. Minecraft refuses chat over 256 characters, and a bot',
  '   that spams chat gets kicked by the server.',
  '6. Say what the addon does in the description, in one sentence, plainly.',
  '',
  'Now write the addon for this idea:'
];

/** The prompt, as one block of text with a trailing blank line for appending. */
export const ADDON_PROMPT = `${LINES.join('\n')}\n`;
